### ISSUE TITLE
Implement web3signer `healthcheck` + `depends_on`

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/StakingBrain#135]
When implementing the staking brain in the web3signer, make sure to add to the `signer` compose service a [healthcheck](https://docs.docker.com/compose/compose-file/compose-file-v3/#healthcheck) like:
```
  healthcheck: 
    test: ["CMD", "curl", "-f", "http://web3signer.dappnode:9000/ok"]
    interval: 1m30s
    timeout: 10s
    retries: 100
    start_period: 5s
```
Also implement a `depends_on` in the brain compose service to depend on the signer
```
  depends_on: web3signer
```
This should make sure to start the brain only once the signer is ready (as the signer is been started only once the db is ready)
