### ISSUE TITLE
Invalid auth token

### ISSUE THREAD

**Issue by angyts** [dappnode/StakingBrain#359]
**Describe the bug**

The Ethereum validator detects no valid validators, although the keys are load onto the web3signer. 

**To Reproduce**

Dappnode OS is installed
The validator docker storage location was changed.
The web3signer brain shows this error message.

```json
[ERROR] Error reloading data
ApiError: FORBIDDEN: Invalid auth token: Bearer api-token-0x0200e6ce18e26fd38caca7ae1bfb9e2bba7efb20ed2746ad17f2f6dda44603152dError getting (GET) remote keys from validator. HTTP error code 403
    at IncomingMessage.<anonymous> (file:///app/packages/brain/dist/modules/apiClients/standard.js:131:32)
    at IncomingMessage.emit (node:events:523:35)
    at endReadableNT (node:internal/streams/readable:1367:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ERR_HTTP',
  errno: 403,
  path: '/eth/v1/remotekeys',
  syscall: 'GET',
  hostname: 'validator.lighthouse-holesky.dappnode',
  address: undefined,
  port: undefined
}
```

**Expected behavior**

Validator and web3signer should be able to communicate. I tried to restart the containers, but still the same.

**Comment by pablomendezroyo** [comment]
Hi there! which clients are you using

**Comment by angyts** [comment]
Hi im using 
Lighthouse and Nethermind. 

I believe this one seems to be a problem with lighthouse communicating with the brain

**Comment by pablomendezroyo** [comment]
Can you share the logs from the validator lighthouse holesky service?

**Comment by pablomendezroyo** [comment]
Also what do you mean by `The validator docker storage location was changed.`? 

Try re-selecing your clients in the stakers UI

**Comment by angyts** [comment]
> Can you share the logs from the validator lighthouse holesky service?

```bash
Sep 27 16:20:54.001 INFO Connected to beacon node(s)             synced: 1, available: 1, total: 1, service: notifier
Sep 27 16:20:54.001 INFO No validators present                   msg: see `lighthouse vm create --help` or the HTTP API documentation, service: notifier
Sep 27 16:21:06.000 INFO Connected to beacon node(s)             synced: 1, available: 1, total: 1, service: notifier
Sep 27 16:21:06.000 INFO No validators present                   msg: see `lighthouse vm create --help` or the HTTP API documentation, service: notifier
```

**Comment by angyts** [comment]
> Also what do you mean by `The validator docker storage location was changed.`?
> 
> Try re-selecing your clients in the stakers UI

```yml
version: '3.5'
services:
  beacon-chain:
    container_name: DAppNodePackage-beacon-chain.lighthouse-holesky.dnp.dappnode.eth
    environment:
      - LOG_LEVEL=info
      - CHECKPOINT_SYNC_URL=https://checkpoint-sync-holesky.dappnode.io
      - EXTRA_OPTS=--target-peers=50
      - FEE_RECIPIENT_ADDRESS
      - CORSDOMAIN=http://lighthouse-holesky.dappnode
      - _DAPPNODE_GLOBAL_MEVBOOST_HOLESKY=true
    image: beacon-chain.lighthouse-holesky.dnp.dappnode.eth:0.1.4
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
    networks:
      dncore_network:
        aliases:
          - beacon-chain.lighthouse-holesky.dappnode
          - beacon-chain.holesky.dncore.dappnode
      holesky_network:
        aliases:
          - beacon-chain.holesky.staker.dappnode
    ports:
      - '9604:9604'
      - 9604:9604/udp
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
    volumes:
      - /media/ssd/beacon-data:/root/.lighthouse
    labels:
      dappnode.dnp.dnpName: lighthouse-holesky.dnp.dappnode.eth
      dappnode.dnp.version: 0.1.4
      dappnode.dnp.serviceName: beacon-chain
      dappnode.dnp.dependencies: '{}'
      dappnode.dnp.avatar: /ipfs/QmU89HuSamscTXZnYLm11Gj2a9jfP1zSZUXuHbUpaHXoP7
      dappnode.dnp.chain: >-
        {"driver":"ethereum-beacon-chain","serviceName":"beacon-chain","portNumber":3500}
      dappnode.dnp.isCore: 'false'
      dappnode.dnp.default.environment: >-
        ["LOG_LEVEL=info","CHECKPOINT_SYNC_URL=https://checkpoint-sync-holesky.dappnode.io","EXTRA_OPTS=--target-peers=50","FEE_RECIPIENT_ADDRESS","CORSDOMAIN=http://lighthouse-holesky.d>
      dappnode.dnp.default.ports: '["9604:9604","9604:9604/udp"]'
      dappnode.dnp.default.volumes: '["beacon-data:/root/.lighthouse"]'
  validator:
    container_name: DAppNodePackage-validator.lighthouse-holesky.dnp.dappnode.eth
    environment:
      - LOG_LEVEL=info
      - GRAFFITI=validating_from_DAppNode
      - EXTRA_OPTS
      - FEE_RECIPIENT_ADDRESS=0xE73a3602b99f1f913e72F8bdcBC235e206794Ac8
      - ENABLE_DOPPELGANGER=true
      - _DAPPNODE_GLOBAL_MEVBOOST_HOLESKY=true
    image: validator.lighthouse-holesky.dnp.dappnode.eth:0.1.4
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
    networks:
      dncore_network:
        aliases:
          - validator.lighthouse-holesky.dappnode
          - validator.holesky.dncore.dappnode
      holesky_network:
        aliases:
          - validator.holesky.staker.dappnode
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
    volumes:
      - /media/ssd/validator-data:/root/.lighthouse/validators
    labels:
      dappnode.dnp.dnpName: lighthouse-holesky.dnp.dappnode.eth
      dappnode.dnp.version: 0.1.4
      dappnode.dnp.serviceName: validator
      dappnode.dnp.dependencies: '{}'
      dappnode.dnp.avatar: /ipfs/QmU89HuSamscTXZnYLm11Gj2a9jfP1zSZUXuHbUpaHXoP7
      dappnode.dnp.chain: >-
        {"driver":"ethereum-beacon-chain","serviceName":"beacon-chain","portNumber":3500}
      dappnode.dnp.isCore: 'false'
      dappnode.dnp.default.environment: >-
        ["LOG_LEVEL=info","GRAFFITI=validating_from_DAppNode","EXTRA_OPTS","FEE_RECIPIENT_ADDRESS=0xE73a3602b99f1f913e72F8bdcBC235e206794Ac8","ENABLE_DOPPELGANGER=true","_DAPPNODE_GLOBAL>
networks:
  dncore_network:
    external: true
  holesky_network:
    external: true
```
